### ISSUE TITLE
fix(ux): refresh proposals list after create/update/cancel

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#102]
For offchain spaces

**Comment by wa0x6e** [comment]
This is a necessary feature, but is needed only for offchain spaces. Need to find an approach to implement that, without having offchain only features everywhere.

**Comment by bonustrack** [comment]
It's also needed for onchain actions, even if it work differently and action is confirmed only after a delay

**Comment by wa0x6e** [comment]
If there's a delay, we should not trigger actions after tx is validated, else the UI will do something while user is not expecting it

**Comment by wa0x6e** [comment]
We could refresh some part of the UI (like proposals results), but no redirect
