### ISSUE TITLE
bug: Wrong voting power everywhere 

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/sx-monorepo#1036]
- address `0x74fa01a5D0ef8039f1E14F4d4C8f90e8602e07B4` who have voting power, proof of voting power on [playground link](https://v1.snapshot.box/#/playground/erc20-balance-of-weighted?query=eyJwYXJhbXMiOnsic3ltYm9sIjoiYmZXRVRIIiwid2VpZ2h0IjoyNTAwLCJhZGRyZXNzIjoiMHgyM0NkMzFiZUVjODk4MEU3RjhBRWI3RTc2RDQ1RmUzZGE0ZGUxNTkyIiwiZGVjaW1hbHMiOjE4fSwic3BhY2UiOiIiLCJuZXR3b3JrIjoiODQ1MyIsInNuYXBzaG90IjoiMjM1MTg4NzkiLCJhZGRyZXNzZXMiOlsiMHg3NGZhMDFhNUQwZWY4MDM5ZjFFMTRGNGQ0QzhmOTBlODYwMmUwN0I0Il19)
- Go to the Profile page https://snapshot.box/#/s:black-flag.eth/profile/0x74fa01a5D0ef8039f1E14F4d4C8f90e8602e07B4 Shows `0` voting power

- Go to [proposal](http://127.0.0.1:8080/#/s:black-flag.eth/proposal/0x2b1c20196a974edb3f487964b300119063d4acb4ec80448117b152b725fc2907/votes):
![image](https://github.com/user-attachments/assets/03515d10-940e-4d4a-80c5-8ff06e33e982)
![image](https://github.com/user-attachments/assets/18c0140f-e1bd-4feb-895c-9d1acefc0230)

- Go to proposals Page: 
![Untitled 6](https://github.com/user-attachments/assets/f7ec5328-4060-4d20-a920-9cf5639aaa61)

**Comment by wa0x6e** [comment]
Is this a formatting issue ? the query from score-api return the correct result, and some space like safe show the correct VP for its users

**Comment by wa0x6e** [comment]
It that only for spaces on BASE ?
