### ISSUE TITLE
feat: Support edit profile

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#123]
Using sessions keys, it should be possible for an user on Ethereum or Starknet to setup his profile. His profile would includes:

 - Name: A name with a max of 50 chars
- About: A text with a max of 160 chars
- Avatar image: Image uploaded on IPFS and resolved by Stamp
- Social account: X, GitHub, Discord, Discourse

The profile should be stored on Highlight using the agent "profiles".

**Comment by aurelianoB** [comment]
Closing as already solved by https://github.com/snapshot-labs/sx-monorepo/issues/387
