### ISSUE TITLE
bug: Connector stuck loading Starknet

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/sx-monorepo#126]
When I select the connector Startnet > Argent X, but I reject the connection the Navbar connect button will be stuck in infinite loading.

Also when I logout and then connect again selecting Starknet, I no longer get the 3 options on how I would like to connect to Starknet, it just connects me right away. So it seems after connecting once I no longer have the option to change it

**Comment by wa0x6e** [comment]
No longer reproducible
