### ISSUE TITLE
bug(ui): progress background is votes page is not positioned correctly on Safari 

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#145]
This UI issue is on Safari mobile/desktop, and Google chrome iOS

![Screenshot 2024-03-07 at 19 05 54](https://github.com/snapshot-labs/sx-monorepo/assets/495709/89e3b75c-c622-408d-9089-aa8287a586c7)

You can test by going to any votes page (eg: https://snapshotx.xyz/#/s:safe.eth/proposal/0x1d65ca5270b4aa1efaa7b7ca4e17976a99b802efcf678ac2909eb836b1662a29/votes) on safari mobile(iOS)/desktop (os x) or Google chrome on iPhone

**Comment by wa0x6e** [comment]
**Cause:** The progress `<div>` is a child of `<tr>`, which is not valid, as `<td>` is the only valid child type

**Comment by wa0x6e** [comment]
Tried using `linear-gradient` on `tr`, but it still gives weird result on safari, it repeats the gradient for each `td`.

![Image](https://github.com/snapshot-labs/sx-monorepo/assets/495709/c87077b8-7053-4f0b-9bc7-afbbf79ed963)

Any more ideas @samuveth ?

I tried a few solution, and did not find something usable.

In the meantime, we could target only safari, and hide the bug via CSS

**Comment by Sekhmet** [comment]
https://bugs.webkit.org/show_bug.cgi?id=240961

**Comment by wa0x6e** [comment]
Seems like it's also happening on Google Chrome iOS

**Comment by Sekhmet** [comment]
> Seems like it's also happening on Google Chrome iOS

All iOS browsers will be affected, because WebKit is only allowed engine on iOS.

**Comment by bonustrack** [comment]
Wouldn't using div instead of table fix this issue?

**Comment by wa0x6e** [comment]
Yes, but doesn't guarantee every column have the same size on all rows

**Comment by bonustrack** [comment]
Not worrying about this, I did lot of table like UI and never used `<table>`. Maybe this change can be done in same time than #331

**Comment by Sekhmet** [comment]
@wa0x6e do you want to take on this task migrating off from `table`?

**Comment by wa0x6e** [comment]
On it
