### ISSUE TITLE
bug: Voting power display is failing when not integer

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#146]
Offchain strategies may sometimes return decimal voting power, such as `2545883.183594644`

It seems that current UI expect an integer voting power, and fails with

```
Failed to load voting power RangeError: The number 2545883.183594644 cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at index--Vzf1EyZ.js:397:41963
    at Array.map (<anonymous>)
    at Object.getVotingPower (index--Vzf1EyZ.js:397:41891)
    at async Object.getVotingPower (index--Vzf1EyZ.js:540:7341)
    at async Tn (index--Vzf1EyZ.js:692:67786)
```

**Comment by wa0x6e** [comment]
@Sekhmet The `VotingPower` type is expecting the `value` to be a `bigint`. This is more a architecture issue than a bug issue.

I am not knowledgable enough to know if the use of BigInt is required on the other network type, but for offchain scores, we compute everything using the basic `Number` type from javascript, and don't support big number but support floating number.

**Comment by Sekhmet** [comment]
What space/strategy does it happen to?

We use bigint because we wanted precise values. So instead of 0.000000000001 we store 1n knowing it used 12 decimals for example.

We parse those using configured decimals:
https://github.com/snapshot-labs/sx-monorepo/blob/2ccb1537c2fc25c82fd1bf231bb8543703292d70/packages/sx.js/src/strategies/offchain/remote-vp.ts#L21-L26

I assume this happens because it doesn't have decimals configured but still uses decimal value. I guess we have to take a look at specific strategy and see why it doesn't have decimals.

If we can't change it for those, we could instead pick some value and just use it for decimals by default:
```diff
diff --git a/apps/ui/src/networks/offchain/actions.ts b/apps/ui/src/networks/offchain/actions.ts
index 86791d69..3aba481f 100644
--- a/apps/ui/src/networks/offchain/actions.ts
+++ b/apps/ui/src/networks/offchain/actions.ts
@@ -184,7 +184,7 @@ export function createActions(
 
       return result.map((value: bigint, index: number) => {
         const strategy = strategiesOrValidationParams[index];
-        const decimals = parseInt(strategy.params.decimals || 0);
+        const decimals = parseInt(strategy.params.decimals || 18);
 
         return {
           address: strategy.name,
diff --git a/packages/sx.js/src/strategies/offchain/remote-vp.ts b/packages/sx.js/src/strategies/offchain/remote-vp.ts
index 29cdd796..14ea7a8d 100644
--- a/packages/sx.js/src/strategies/offchain/remote-vp.ts
+++ b/packages/sx.js/src/strategies/offchain/remote-vp.ts
@@ -20,9 +20,9 @@ export default function createRemoteVpStrategy(): Strategy {
 
       return result.vp_by_strategy.map((vp: number, i: number) => {
         const strategy = params[i];
-        const decimals = parseInt(strategy.params.decimals || 0);
+        const decimals = parseInt(strategy.params.decimals || 18);
 
-        return BigInt(vp * 10 ** decimals);
+        return BigInt(Math.floor(vp * 10 ** decimals));
       });
     }
   };
```

**Comment by wa0x6e** [comment]
See https://snapshotx.xyz/#/s:safe.eth/proposal/0x1d65ca5270b4aa1efaa7b7ca4e17976a99b802efcf678ac2909eb836b1662a29/votes

**Comment by wa0x6e** [comment]
> See https://snapshotx.xyz/#/s:safe.eth/proposal/0x1d65ca5270b4aa1efaa7b7ca4e17976a99b802efcf678ac2909eb836b1662a29/votes

In this particular case, testing with the address `0x8C28Cf33d9Fd3D0293f963b1cd27e3FF422B425c`, the score-api returns:

```
{"jsonrpc":"2.0","result":{"vp":2545883.183594644,"vp_by_strategy":[0,2545883.183594644,0],"vp_state":"final"},"id":null,"cache":false}
```

Which match the 2.M voting power, from the playground https://snapshot.org/#/playground/delegation?query=eyJwYXJhbXMiOnsic3ltYm9sIjoiU0FGRSAoZGVsZWdhdGVkKSIsInN0cmF0ZWdpZXMiOlt7Im5hbWUiOiJlcmMyMC1iYWxhbmNlLW9mIiwicGFyYW1zIjp7InN5bWJvbCI6IlNBRkUiLCJhZGRyZXNzIjoiMHg1YWZlMzg1NTM1OGUxMTJiNTY0N2I5NTI3MDllNjE2NWUxYzFlZWVlIiwiZGVjaW1hbHMiOjE4fX0seyJuYW1lIjoic2FmZS12ZXN0ZWQiLCJwYXJhbXMiOnsiY2xhaW1EYXRlTGltaXQiOiIyMDIyLTEyLTI3VDEwOjAwOjAwKzAwOjAwIiwiYWxsb2NhdGlvbnNTb3VyY2UiOiJodHRwczovL3NhZmUtY2xhaW1pbmctYXBwLWRhdGEuZ25vc2lzLXNhZmUuaW8vYWxsb2NhdGlvbnMvMS9zbmFwc2hvdC1hbGxvY2F0aW9ucy1kYXRhLmpzb24ifX1dLCJkZWxlZ2F0aW9uU3BhY2UiOiJzYWZlLmV0aCJ9LCJuZXR3b3JrIjoiMSIsInNuYXBzaG90IjoiMTkzODg4MzkiLCJhZGRyZXNzZXMiOlsiMHg4QzI4Q2YzM2Q5RmQzRDAyOTNmOTYzYjFjZDI3ZTNGRjQyMkI0MjVjIl19

Seems that when voting, the above vp of `2545883.183594644` will be used by snapshot v1, and not the one after decimal correction. (See the votes table in the hub, the vp column is full of decimal numbers)

**Comment by Sekhmet** [comment]
Thank you, I'd just default to bigger decimals instead of 0 to conserve as much decimals as we can (within reason) and floor it if still not enough.

```diff
diff --git a/apps/ui/src/networks/offchain/actions.ts b/apps/ui/src/networks/offchain/actions.ts
index 86791d69..36e2d78b 100644
--- a/apps/ui/src/networks/offchain/actions.ts
+++ b/apps/ui/src/networks/offchain/actions.ts
@@ -164,7 +164,7 @@ export function createActions(
 
       const result = await strategy.getVotingPower(
         spaceId,
-        voterAddress,
+        '0x8C28Cf33d9Fd3D0293f963b1cd27e3FF422B425c',
         strategiesOrValidationParams,
         snapshotInfo
       );
@@ -184,7 +184,7 @@ export function createActions(
 
       return result.map((value: bigint, index: number) => {
         const strategy = strategiesOrValidationParams[index];
-        const decimals = parseInt(strategy.params.decimals || 0);
+        const decimals = parseInt(strategy.params.decimals || 18);
 
         return {
           address: strategy.name,
diff --git a/packages/sx.js/src/strategies/offchain/remote-vp.ts b/packages/sx.js/src/strategies/offchain/remote-vp.ts
index 29cdd796..14ea7a8d 100644
--- a/packages/sx.js/src/strategies/offchain/remote-vp.ts
+++ b/packages/sx.js/src/strategies/offchain/remote-vp.ts
@@ -20,9 +20,9 @@ export default function createRemoteVpStrategy(): Strategy {
 
       return result.vp_by_strategy.map((vp: number, i: number) => {
         const strategy = params[i];
-        const decimals = parseInt(strategy.params.decimals || 0);
+        const decimals = parseInt(strategy.params.decimals || 18);
 
-        return BigInt(vp * 10 ** decimals);
+        return BigInt(Math.floor(vp * 10 ** decimals));
       });
     }
   };
```

Should be enough for UI.

**Comment by wa0x6e** [comment]
> Thank you, I'd just default to bigger decimals instead of 0 to conserve as much decimals as we can (within reason) and floor it if still not enough.
> 
> diff --git a/apps/ui/src/networks/offchain/actions.ts b/apps/ui/src/networks/offchain/actions.ts
> index 86791d69..36e2d78b 100644
> --- a/apps/ui/src/networks/offchain/actions.ts
> +++ b/apps/ui/src/networks/offchain/actions.ts
> @@ -164,7 +164,7 @@ export function createActions(
>  
>        const result = await strategy.getVotingPower(
>          spaceId,
> -        voterAddress,
> +        '0x8C28Cf33d9Fd3D0293f963b1cd27e3FF422B425c',
>          strategiesOrValidationParams,
>          snapshotInfo
>        );
> @@ -184,7 +184,7 @@ export function createActions(
>  
>        return result.map((value: bigint, index: number) => {
>          const strategy = strategiesOrValidationParams[index];
> -        const decimals = parseInt(strategy.params.decimals || 0);
> +        const decimals = parseInt(strategy.params.decimals || 18);
>  
>          return {
>            address: strategy.name,
> diff --git a/packages/sx.js/src/strategies/offchain/remote-vp.ts b/packages/sx.js/src/strategies/offchain/remote-vp.ts
> index 29cdd796..14ea7a8d 100644
> --- a/packages/sx.js/src/strategies/offchain/remote-vp.ts
> +++ b/packages/sx.js/src/strategies/offchain/remote-vp.ts
> @@ -20,9 +20,9 @@ export default function createRemoteVpStrategy(): Strategy {
>  
>        return result.vp_by_strategy.map((vp: number, i: number) => {
>          const strategy = params[i];
> -        const decimals = parseInt(strategy.params.decimals || 0);
> +        const decimals = parseInt(strategy.params.decimals || 18);
>  
> -        return BigInt(vp * 10 ** decimals);
> +        return BigInt(Math.floor(vp * 10 ** decimals));
>        });
>      }
>    };
> Should be enough for UI.

This unsync the score and the voting power, showing people they have 1 ^^18 voting power, but when they vote, it increases the total score only by 1

**Comment by Sekhmet** [comment]
I'm not sure what you mean, in this case it should increase total score by 2.5M? And with my suggested change it displays it as 2.5M as well.
