### ISSUE TITLE
bug: `space` params missing when fetching offchain voting power

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#147]
Offchain voting power fetching API was reusing already existing code, to avoid changing functions signature too much

Particulary, this one

https://github.com/snapshot-labs/sx-monorepo/blob/a24c3c0c30d15c9dec06fe85f65227754ffbbc2d/apps/ui/src/views/Editor.vue#L230-L239

Now, it seems like a `space` params is needed by some strategies (such as those using delegation), requiring addition to the function above, to inject an additional readonly `space` params

Should we change the signature to :

```js
getVotingPower(
    strategiesAddresses: string[],
    strategiesParams: any[],
    strategiesMetadata: StrategyParsedMetadata[],
    voterAddress: string,
    snapshotInfo: SnapshotInfo,
    extra: Record<string, string>
  ): Promise<VotingPower[]>;
```

with the new `extra` (or maybe `payload` ?) argument taking something like `{ space: 'ens.eth' }`. Being an object will open possibilities of adding more read-only data in the future.

And putting it last on the args list will let us avoid refactoring networks not using it.

Wdyt @Sekhmet ?

```[tasklist]
### Tasks
- [ ] https://github.com/snapshot-labs/sx-monorepo/pull/160
```

**Comment by Sekhmet** [comment]
I think I'd just add `spaceAddress` as first argument (and refactor it as-needed), it seems important enough (in generic sense, as in case of SX it wasn't really needed) to make it first-party argument.
