### ISSUE TITLE
feat: add voting for offchain spaces

### ISSUE THREAD

**Issue by Sekhmet** [snapshot-labs/sx-monorepo#15]
## Framing

- Give users the ability to vote on offchain spaces from SX-UI.

## Design/UX

- We should reuse the same UI components used for onchain voting.

## Engineering

- Exclude the following voting types:
    - Shutter shielded voting
    - weighted
    - quadratic
    - RCV
    
## Technical spec
 
1. All actions (including voting) are performed using `useActions` composable:
https://github.com/snapshot-labs/sx-monorepo/blob/b67b54158e5eee49c77f77507b876a3c176449e4/apps/ui/src/components/ProposalsListItem.vue#L17
https://github.com/snapshot-labs/sx-monorepo/blob/500886339a06e7c81f88a368d75a9676c973fc4a/apps/ui/src/composables/useActions.ts#L185-L209

2. Those UI actions then call appropriate action on network configuration, for example [`vote`](https://github.com/snapshot-labs/sx-monorepo/blob/21a3dd72476682ce97bede730787501cf75064d3/apps/ui/src/networks/types.ts#L138-L144).

3. Currently `offchain` network doesn't support `vote` action as it's read only space (which for now only includes `getVotingPower` action, for now I'd suggest moving `vote` action to `ReadOnlyNetworkActions`:
https://github.com/snapshot-labs/sx-monorepo/blob/21a3dd72476682ce97bede730787501cf75064d3/apps/ui/src/networks/types.ts#L82-L90

This won't be ideal as the naming is a bit inaccurate for the time being (`vote` could be considered `write` action), unless we consider `write` to mean "can create new space" - I think we can think about it later, maybe we should have more granular types later instead of `ReadWrite` and space can advertise every action individually.

4. After that we can define `vote` action for `offchain` network [here](https://github.com/snapshot-labs/sx-monorepo/blob/21a3dd72476682ce97bede730787501cf75064d3/apps/ui/src/networks/offchain/index.ts#L68). What this action needs to do is unclear to me, you might be more knowledgable here or can use Snapshot source as reference. Might be worth to extract actions into separate `actions.ts` file at this point similar to other networks.

5. After that we will need to make Vote actions to show up here, but making sure we only show it if voting type is supported: https://github.com/snapshot-labs/sx-monorepo/blob/21a3dd72476682ce97bede730787501cf75064d3/apps/ui/src/views/Proposal.vue#L162

6. Right now we add pending transaction for all actions, we might want to add special case here to handle cases where it's not needed: https://github.com/snapshot-labs/sx-monorepo/blob/500886339a06e7c81f88a368d75a9676c973fc4a/apps/ui/src/composables/useActions.ts#L75-L82

**Comment by wa0x6e** [comment]
For now, should we support only voting from wallet, and ignore safe wallet?

**Comment by bonustrack** [comment]
Yes @wa0x6e
