### ISSUE TITLE
fix(ui): return 0 voting power on Snapshot spaces if user is logged with Starknet account

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#155]
Currently if you connect a Starknet wallet and go on a Snapshot space in the proposals or proposal pages, the voting power will be queried and fail. This is because we don't support Starknet addresses on the Score API. We should instead skip voting power calculation and just show 0 as voting power.
```[tasklist]
### Tasks
- [ ] https://github.com/snapshot-labs/sx-monorepo/pull/165
```

**Comment by wa0x6e** [comment]
I guess we should also do the same for the opposite, do not show voting power for starknet spaces when connected with a non-starknet account ?
