### ISSUE TITLE
feat(api): store proposal_count and vote_count per user per space

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#157]
We should store in SX API and subgraph the values "proposal_count" and "vote_count" per user per space. The entity to store this information can be called "leaderboard" with these params:

- user
- space
- proposal_count
- vote_count

**Comment by wa0x6e** [comment]
Isn't this related to https://github.com/snapshot-labs/snapshot-sequencer/pull/127 ?
