### ISSUE TITLE
bug: missing choice on votes page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#202]
Choice is not visible on this proposal:
https://snapshotx.xyz/#/s:balancer.eth/proposal/0xe7e8d3af73be6ac1af52c117722c3a0bc6c4d82c3d77a341c2a63eff607cca49/votes
https://snapshot.org/#/balancer.eth/proposal/0xe7e8d3af73be6ac1af52c117722c3a0bc6c4d82c3d77a341c2a63eff607cca49

**Comment by Sekhmet** [comment]
This PR will add support for it: https://github.com/snapshot-labs/sx-monorepo/pull/175
