### ISSUE TITLE
feat: add timeline

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#217]
We should have a new page on SX UI with a feed including proposals from all spaces I follow, it can look like the "proposals" page, just adding space name and image. This is similar as what we've done on Snapshot here: https://snapshot.org/#/timeline

This should be the homepage for logged users. When opening the page here: https://snapshotx.xyz we should see the landing page first, if user become logged we would redirect him to https://snapshotx.xyz/#/home (if he was on the homepage only) with the feed of proposals. We can have the same layout as Space pages with sidebar in left, we can use the sidebar from Settings and MySpaces pages and add "Followings".

<img width="1469" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/09a9be54-d363-47d8-8310-5b8791fef09b">

More TBD

**Comment by bonustrack** [comment]
Not from favorite, from all follows, we will add follows later on

**Comment by wa0x6e** [comment]
So this is just showing for Follows, but we don't have way to know which spaces are followed, nor have a way to follow/unfollow spaces on v2, we just pull the list from the hub

**Comment by bonustrack** [comment]
Well, you need to query the list of following from the hub

**Comment by wa0x6e** [comment]
Do you have a UI draft about how to show the space in the proposals list ?

**Comment by bonustrack** [comment]
We can do like this for now:
<img width="927" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/c6734f95-d898-47ab-8635-40e24b0afc05">

**Comment by wa0x6e** [comment]
What does the page do for guest users ? When they access this page directly with the url ?

**Comment by bonustrack** [comment]
It should lead you to the landing page

**Comment by bonustrack** [comment]
Similar than Twitter

**Comment by wa0x6e** [comment]
It feels weird to only have `Followings` using a redirection to landing page for guest user, and not have them on `My Spaces` and `Contacts`.

We should either have it everywhere or nowhere.
