### ISSUE TITLE
feat: sort results choices by weight

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#227]
We should sort results choices by total weight, see difference between this:
https://snapshotx.xyz/#/s:ens.eth/proposal/0x6ba81cd2997288cc49ae1b95921ec8f107e8ffb9733321d53d488e2b30710b86
And here: https://snapshot.org/#/ens.eth/proposal/0x6ba81cd2997288cc49ae1b95921ec8f107e8ffb9733321d53d488e2b30710b86

**Comment by wa0x6e** [comment]
Do we also need to sort them for basic voting type, or we keep current For, against, abstain order ?
