### ISSUE TITLE
bug: votes weight background break after casting a vote

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#235]
When I cast a vote and go on the votes page, I can see the weight is broken (it most likely use the total scores prior to my vote) see:

<img width="1469" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/6747ea45-85b0-4970-aef6-01e01fbb4c9b">

**Comment by wa0x6e** [comment]
How to reproduce ? Connected to shot.eth with guest, and can not reproduce

**Comment by bonustrack** [comment]
You need to cast a vote, and switch to votes tab without refreshing the page to see the bug.

**Comment by wa0x6e** [comment]
mhhhh, I see. I also see that I have unlimited voting power

![Screenshot 2024-04-03 at 20 03 57](https://github.com/snapshot-labs/sx-monorepo/assets/495709/6250a84c-878b-440b-a6fe-82321298d9ad)

**Comment by bonustrack** [comment]
This is another issue

**Comment by bonustrack** [comment]
You need to vote with an account with 1 VP then vote with another account with 2 VP and check votes page
