### ISSUE TITLE
feat: add leaderboard page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#250]
Using same layout than delegates page, we should add a leaderboard page with ranking of users based on number of proposals or votes, this is should be integrated for SX first, for Snapshot spaces the API is WIP.
<img width="1455" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/83b4cfdd-4d8c-4ce3-8ee4-604a8359b92f">

**Comment by wa0x6e** [comment]
What's the API looks like on the sx ? So we can reproduce the same on the hub for consistency
