### ISSUE TITLE
bug: Rabby wallet trigger when opening a page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#255]
I have both Metamask and Rabby wallet in my Chrome browser. When Rabby is locked everytime I open a page on Snapshot or SX it go trigger to unlock, this is support annoying. 

<img width="1469" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/eb738200-bcec-4971-828d-7be49249eeb7">

**Comment by wa0x6e** [comment]
Is the Rabby wallet prompt on page load, or only when trying to login ?

**Comment by bonustrack** [comment]
On page load

**Comment by wa0x6e** [comment]
And you're still logged in via Metamask ?

**Comment by bonustrack** [comment]
Non

**Comment by wa0x6e** [comment]
Will resolve via https://github.com/snapshot-labs/lock/issues/109

**Comment by wa0x6e** [comment]
Can you test https://github.com/snapshot-labs/lock/pull/110 and confirm that it fixes the issue ? Can not reproduce the rabby wallet prompt on my end

**Comment by wa0x6e** [comment]
Should be fixed via https://github.com/snapshot-labs/sx-monorepo/pull/839
