### ISSUE TITLE
bug: space treasure failing

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#258]
https://snapshotx.xyz/#/s:stgdao.eth/treasury

Space treasury crashes the whole page with

![Screenshot 2024-04-06 at 20 57 47](https://github.com/snapshot-labs/sx-monorepo/assets/495709/16e2a2d6-2541-4fb2-a8f7-0859cf318314)

**Comment by bonustrack** [comment]
Yes this is because of Alchemy or Coingecko limit on number of tokens, we will need to chunk the requests

**Comment by wa0x6e** [comment]
After investigation, this page crashes because of invalid results returned by Alchemy getTokenMetadata request.

Error is in 2 forms:

### Unrecognized tokens

```shell
curl 'https://eth-mainnet.g.alchemy.com/v2/ombBQyf580z-jx2EVQgJu4eTjePU-a2z' \
  -H 'accept: */*' \
  -H 'content-type: text/plain;charset=UTF-8' \
  --data-raw '[{"id":0,"jsonrpc":"2.0","method":"alchemy_getTokenMetadata","params":["0x00a7ba8ae7bca0b10a32ea1f8e2a1da980c6cad2"]}]'
```

which return

```
{"jsonrpc":"2.0","id":0,"error":{"code":-32602,"message":"Invalid params: expected a valid token contract address."}}
``` 

Seems like some tokens in the treasury are not recognized by alchemy, the contract exist on etherscan https://etherscan.io/address/0x00a7ba8ae7bca0b10a32ea1f8e2a1da980c6cad2

### Rate limit error 

On treasuries with lot of tokens, like the one from stgdao.eth, we're simply being throttled by alchemy

```
{
  "jsonrpc": "2.0",
  "id": 2,
  "error": {
    "code": 429,
    "message": "Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemy.com/reference/throughput"
  }
}
```
