### ISSUE TITLE
feat: display quorum %

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#279]
We should display the quorum of a proposal on the proposal page, here is how it would look like:

<img width="889" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/31ed48f7-6704-4dde-b2ad-097be4a71559">

Quorum should also be visible in the feed like this:
<img width="1196" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/da7305f5-9c46-44ef-b184-ca96028032d7">

We should use max 2 decimals in the percentage.

**Comment by wa0x6e** [comment]
Not using https://github.com/snapshot-labs/sx-monorepo/issues/275 ?

**Comment by wa0x6e** [comment]
What words should be used for quorum of rejection ?

**Comment by bonustrack** [comment]
"Quorum of reject"

**Comment by wa0x6e** [comment]
Quorum of reject will always be `0%` until the proposal is closed, may be misleading

**Comment by bonustrack** [comment]
Why is that?

**Comment by wa0x6e** [comment]
Because it depends on people who vote AGAINST, or choice index 1

**Comment by wa0x6e** [comment]
And its' weird on shutter proposal, with the message center aligned

![Screenshot 2024-04-16 at 00 18 10](https://github.com/snapshot-labs/sx-monorepo/assets/495709/b2292e15-dbcb-47cc-8575-d02fd6830306)
