### ISSUE TITLE
feat: add profile and settings on home sidebar

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#292]
In the home sidebar we should add a link to the user profile and settings pages, using "user" and "cog" icons like this:
<img width="842" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/fc90867a-8d8c-4d2d-b75e-71c0efa0d3a6">

Depend on #217 and #291

**Comment by wa0x6e** [comment]
Is the profile link in the this sidebar different from the user profile link elsewhere ?

**Comment by bonustrack** [comment]
@wa0x6e No

**Comment by wa0x6e** [comment]
This will be weird, since this looks like it will show my profile, but if I click on other user's profile, it will also have this sidebar

**Comment by bonustrack** [comment]
I think I get confused with your comment, profile page shouldn't have sidebar, I'm just saying adding "Profile" to the sidebar for home pages

**Comment by bonustrack** [comment]
Closed on #300
