### ISSUE TITLE
feat: explore page with support for Snapshot spaces

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#297]
On the explore page, we should add a filter for protocol, with the option Snapshot or Snapshot X, see how it would look like:
<img width="1003" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/c16e4c75-da9b-45d8-828c-9d97d4789541">

We should display the list of Snapshot spaces by default, using current ordering from snapshot.org. Here is how the layout would look like:
<img width="1457" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/8ebaddfb-355a-4f7e-8037-352c794bd5ed">

- Also remove the favorite icon on all spaces for now.

**Comment by ChaituVR** [comment]
![image](https://github.com/snapshot-labs/sx-monorepo/assets/15967809/0f2e95fe-546f-4394-97a3-81b809ee75b3)
Should we also add a search field? or we will add it in future?

**Comment by ChaituVR** [comment]
Should we also add pagination similar to snapshot.org? For snapshotX spaces, we display all spaces on page load

**Comment by bonustrack** [comment]
Yes with pagination
