### ISSUE TITLE
bug(mana): sponsor tx fail on SN Sepolia

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#304]
For some reason tx to propose are reverting on SN Sepolia with the error "Insufficient max fee: max fee: Fee(17795935068219), actual fee: Fee(84223699650256)"

Example: https://sepolia.starkscan.co/tx/0x5ed0825e5985aee2a0fea50efee024417dfe110bef0b8a201186a0d1f2137e9

On this space: https://testnet.snapshotx.xyz/#/sn-sep:0x0664207ee8c8687c58a4a72f07152e1e612d5107df894c60501e75a665915bf4

**Comment by bonustrack** [comment]
Got this error now on this space: https://testnet.snapshotx.xyz/#/sn-sep:0x0296c8c33760092c8006387c7bd77e1070f9851d49f949bb9c7adff32b4d5982/create/bjaqh
<img width="831" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/70c250a5-d10e-4c14-8b60-81413c7d3de8">

**Comment by Sekhmet** [comment]
Only errors I see are from rate limits:
> 63: An unexpected error occurred: "HTTP status client error (429 Too Many Requests) for url (https://alpha-sepolia.starknet.io/gateway/add_transaction)

Not sure why we use starknet.io gateway though 🤔

**Comment by bonustrack** [comment]
@Sekhmet Probably because this is the sequencer (there is only 1 sequencer on Starknet) it's likely to be the only way to broadcast a tx.

**Comment by Sekhmet** [comment]
Can you try to propose again?

Looks like on our side it works fine as we ourselves do not call sequencer - we call RPC to broadcast a transactions but it looks like Infura is getting rate limited on sequencer.

**Comment by bonustrack** [comment]
@Sekhmet Works now

**Comment by Sekhmet** [comment]
I don't think there is anything we can do about it on our side as it looks like to be Infura getting rate-limited by Sequencer.

**Comment by Sekhmet** [comment]
Mana wasn't deployed with new change, can you try again?

**Comment by bonustrack** [comment]
Works now

**Comment by bonustrack** [comment]
Failed again 
https://sepolia.starkscan.co/tx/0xfff954a4677a7d00630a4158c38e3697159ea140a33d0e3c759ad81529c527

**Comment by Sekhmet** [comment]
That is huge difference, it wants over 3 times more for fee (and we already do 1.5x). I guess we could overestimate it by a lot (like 5x) 🤔

**Comment by bonustrack** [comment]
That's weird that we have to define a max fee this way, doing tx to change settings isn't a problem, I wonder what is the difference with propose with sig

**Comment by Sekhmet** [comment]
> That's weird that we have to define a max fee this way, doing tx to change settings isn't a problem, I wonder what is the difference with propose with sig

Those go through Mana and because we have nonce manager we first estimate the transaction and then invoke it (so we have stable nonce in both transactions). And this can get out of sync.

**Comment by bonustrack** [comment]
I see, it's weird the estimate is so much off
