### ISSUE TITLE
style: votes page horizontally scrollable on mobile

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#331]
On mobile and on the page "votes" there isn't enough space to show the content for votes, we should make the table scrollable horizontally, similar than site like https://www.coingecko.com
The cells should have a minum width so it doesnt take extra line, (first cell dont need to be sticky like on coingecko).
![Screenshot_20240509_064527_Chrome](https://github.com/snapshot-labs/sx-monorepo/assets/16245250/e8027726-41a7-4878-8453-b9085290686f)

**Comment by ChaituVR** [comment]
Delegates and leaderboard use similar layout, what should happen to them? same as votes?

**Comment by ChaituVR** [comment]
I had a blocker with `sticky` property on thead, will wait for this https://github.com/snapshot-labs/sx-monorepo/issues/145#issuecomment-2104404066

**Comment by wa0x6e** [comment]
We currently hide some column in smaller screen.

I guess with this feature, we keep columns ?

**Comment by wa0x6e** [comment]
> I had a blocker with `sticky` property on thead, will wait for this [#145 (comment)](https://github.com/snapshot-labs/sx-monorepo/issues/145#issuecomment-2104404066)

Merged, so this can move on

**Comment by ChaituVR** [comment]
`sticky` doesn't work here. we may have to remove the stickiness of this page. also, the vote % in the background for each will not be correct if we allow horizontal scrolling.

**Comment by Sekhmet** [comment]
I bumped it to `Medium` as I think it will require quite a bit of work.

**Comment by wa0x6e** [comment]
@bonustrack What's the decision here, following the issues raised by chaitu ?

**Comment by bonustrack** [comment]
> `sticky` doesn't work here. we may have to remove the stickiness of this page. also, the vote % in the background for each will not be correct if we allow horizontal scrolling.

For the background with vote % if the page is larger than the screen we can make the bg sticky and base the % from the screen width (and not the whole page width). Does it make sense?

**Comment by wa0x6e** [comment]
And we remove sticky?

**Comment by bonustrack** [comment]
For the sticky, I'm not sure what's blocking, we can use div if table is not working

**Comment by wa0x6e** [comment]
Not an issue of table or div, sticky does not simply seem to work when inside overflow: scroll, it does not stick

**Comment by ChaituVR** [comment]
There are two problems with this:

1. If we want sticky nature like below video, we won't able to make it horizontally scrollable
  https://github.com/user-attachments/assets/30bc0a8f-663b-4070-b290-6720dbee1779


2. Not sure how we want to handle voting power in the background, 
    <img width="379" alt="Untitled 2" src="https://github.com/user-attachments/assets/5daa5eb4-1093-431b-892e-2ceb08f7cf39">

 Here we have the same width as the screen, so if a user 50%, it will add a background of half the screen,
 but if we allow horizontal scroll, it may go under the scroll

**Comment by bonustrack** [comment]
Need to figure out a solution to keep the first nav with "Overview, votes, discussion" sticky

**Comment by bonustrack** [comment]
Here is an example of the UX we want done with CSS using Claude 
https://claude.site/artifacts/40c93fdf-5cec-4ed5-b845-232b40385d56
