### ISSUE TITLE
style: improve editor layout

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#336]
We should move voting type and choice selection on a right sidebar, with same size as a proposal right sidebar, by default "Single choice" should be selected. On button click it should open a modal with all the choices without image (similar than on Snapshot).
![image](https://github.com/snapshot-labs/sx-monorepo/assets/16245250/60c12bc8-ac64-44df-873c-854cf8051956)

**Comment by Sekhmet** [comment]
> On button click it should open a modal with all the choices without image (similar than on Snapshot).

I don't think the UI you included is clear about this. This button doesn't suggest you can click on it to change anything, maybe should use chevron down icon instead of checkmark? Now it looks just like there is one option and nothing else.

**Comment by bonustrack** [comment]
@Sekhmet Yes make sense we can use chevron-down instead for the icon

**Comment by Sekhmet** [comment]
@bonustrack What about spaces that don't have voting type selector? Should we in that case use default layout without sidebar?

**Comment by bonustrack** [comment]
@Sekhmet You can keep same layout with the sidebar, we will later add some info about the start and end date of the proposal there.
