### ISSUE TITLE
bug: leaderboard not loading

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#339]
On this page the leaderboard is empty while this space has activity, also there isn't any error or empty placeholder message
https://snapshotx.xyz/#/sn:0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947/leaderboard

**Comment by SandipGyawali** [comment]
@bonustrack is it open to contribute. I can work on frontend.

**Comment by bonustrack** [comment]
@SandipGyawali Ok sure feel free!

**Comment by SandipGyawali** [comment]
![image](https://github.com/snapshot-labs/sx-monorepo/assets/66510112/6af1fc58-c946-44b4-89f4-b6fa9ef656f0)


this is the desired result right ?

**Comment by bonustrack** [comment]
Yes
