### ISSUE TITLE
style: voting power showing too many decimals on votes page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#342]
Voting power on the following page is displayed as `0.000000000000000002 UNI`, instead it should be `~0`. We should show max 3 decimals, if the amount is lower than 0.001 then we show `~0`.

https://testnet.snapshotx.xyz/#/sn-sep:0x019fe8e10c15ced8c06a1052ab9632d6e4cfb0b447525a6779906b081d31f5d3/proposal/5/votes

<img width="1466" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/ae64f89b-63ec-4f75-9078-65b388a52af6">

**Comment by wa0x6e** [comment]
@bonustrack 

- Should we use 3 decimals max, or use `2` like in the "My voting power" indicator ?
- Should we add a tooltip to display the full value ?

**Comment by bonustrack** [comment]
When it's less than 0.001 we can show just ~0. If it's 0.12345678 we can show 0.123, we don't need tooltip

**Comment by bonustrack** [comment]
This is not fixed for me

https://testnet.snapshotx.xyz/#/sn-sep:0x019fe8e10c15ced8c06a1052ab9632d6e4cfb0b447525a6779906b081d31f5d3/proposal/5/votes

<img width="1469" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/fe544a3e-471a-408d-b525-9a204d7156de">

**Comment by Sekhmet** [comment]
It failed to merge due to some conflicts, was later resubmitted: https://github.com/snapshot-labs/sx-monorepo/pull/352
