### ISSUE TITLE
bug: `loadSpaces` for offchain network not returning expected results

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#366]
Following changes introduced in the explore page here https://github.com/snapshot-labs/sx-monorepo/pull/299/files#diff-bd5baa4baaddc3bacf9298391f16d46caafc1a38b3f677c0e72a9ab8a34a7dc6R329

This is making queries which are expecting max 1000 items (as defined in useSpaces) to return only 20 items, e.g. the follow list in the sidebar showing a truncated list of followed spaces.

The `loadSpaces` now queries `ranking`, which have a limit of 20 items max per page, compared to 1000 before with `spaces`

Additionally, seems like ranking and spaces are not swappable, as it's not accepting same set of filters

**Comment by wa0x6e** [comment]
@ChaituVR Is it possible to keep using `spaces` as before, or increase the limit on the hub for  the `ranking` endpoint to 1000 ?

**Comment by ChaituVR** [comment]
I don't think we should show 1000 spaces on the sidebar, on snapshot sequencer a user can follow only 25 spaces. so maybe we could increase the limit to 25 or a little bit higher?

**Comment by wa0x6e** [comment]
Bumping the limit to 25 will resolve the immediate issue of the sidebar, but still may create headache later, as the limit is overriden by a `Math.min()`, and thus hide any errors when we pass a higher limit, although we expect something big, such as 1000 like the other networks

**Comment by wa0x6e** [comment]
Seems like swapping `Space` by `Ranking` in `loadSpaces` is not working, as `Ranking` is not accepting same set of filters, like loading specific spaces with `id_in`, breaking a few things, like the follow list
