### ISSUE TITLE
feat: spaces on sidebar should only be displayed once are all available

### ISSUE THREAD

**Issue by Sekhmet** [snapshot-labs/sx-monorepo#375]
Currently we take optimistic approach - as soon as one space is available we show it, and then the rest will show up.
This makes it so initially you will see 1 space and after some delay the rest will show up:

https://github.com/snapshot-labs/sx-monorepo/assets/1968722/756dcf95-4346-4827-9b8e-963c9603808e

I think after loading icon disappears we should show complete list of followed spaces, without intermediate steps.

What do you think @wa0x6e @bonustrack ?

## To reproduce

1. Go to space page, follow it.
2. Refresh page.

**Comment by bonustrack** [comment]
Agree it should be visible all at once, currently its confusing
