### ISSUE TITLE
feat: vote modals for reason, progress and share

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#386]
When someone click to cast a vote we should have this flow:

1: For Snapshot and SX, open a modal with a loading indicator.
2: For SX only, once the tx or signature is confirmed we should show another loading indicator and a link to the tx.
3: Once the tx is confirmed, we show a check icon, link to share on X, Lens and Farcaster and a link to the tx.

**Please wait for design, this is in progress.**

**Comment by bonustrack** [comment]
The design is here: https://www.figma.com/design/hmHTau1Y1KYzrBBKLQr5QV/%23design?node-id=5686-2582&t=wqHDcnzNZrXk2gK7-0

There will be some slight change in the texts.

**Comment by Sekhmet** [comment]
@bonustrack just to confirm, this is okay to start working on based on those designs? Because original post has message to wait for designs.

**Comment by Sekhmet** [comment]
> link to share on X, Lens and Farcaster

What should the shared message include? Transaction or link to proposal with some message?
