### ISSUE TITLE
feat: user profile

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#387]
We should change the profile page with the latest design. In this design, the page is part of the "My" section, with the menu appearing in left. We should show the username, address, about (from Snapshot API), activity (based on leaderboard) and social accounts.

Here is the link to the design:
https://www.figma.com/design/hmHTau1Y1KYzrBBKLQr5QV/%23design?node-id=5440-8159&t=CLA0Ou2u7iPnngtn-0

This depends on the leaderboard feature, and adding fields in the edit profile section for social accounts.

If leaderboard is not ready, a first step would be to implement the profile without the activity section and social accounts.

**Comment by wa0x6e** [comment]
Putting the profile page inside the My section will show all profiles with the sidebar, even if it's not your own profile. This may be confusing
