### ISSUE TITLE
feat: user space profile

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#388]
Users have a global profile, but they should also have a space specific profile. This page would show the space sidebar left menu, here is the design:

https://www.figma.com/design/hmHTau1Y1KYzrBBKLQr5QV/%23design?node-id=5457-10451&t=CLA0Ou2u7iPnngtn-0

This includes:
- User info (similar than user global profile)
- A tab statement, which would show the delegate statement of the user for the specific space, this can be queried from the Snapshot API. The tab should be hidden if there isn't any statement.

Other features of the user space profile that will be implemented in further issues:
- The list of delegators (similar than #298)
- The list of proposals in the spaces voted on by the user
- The list of votes in the space by the user

**Comment by wa0x6e** [comment]
What should be the url for this new page ?
