### ISSUE TITLE
style: remove background on space avatars

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#399]
We should remove background on space avatar, currently many space have a rounded avatar and it doesn't look great with the gray background, we should remove it. (For others type of avatar we can keep the way is it).

<img width="582" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/b85b8de3-5aa1-4ac3-b3c9-cf661b2b6046">

**Comment by wa0x6e** [comment]
It looks ok on the follow sidebar, but on space, it looks weirder than before

![Screenshot 2024-06-14 at 00 27 46](https://github.com/snapshot-labs/sx-monorepo/assets/495709/8fc60000-a965-4684-999d-637dcf4a0e1b)

We could also remove the border, and it will look like this

![Screenshot 2024-06-14 at 00 30 11](https://github.com/snapshot-labs/sx-monorepo/assets/495709/c48ade73-33b6-4401-b6cc-525ec6d925f2)

But now, some spaces will have round avatar, some square.

With the new User profile page, it seems that the UI direction was to have square avatar for all spaces, and round for user, but not with this change anymore

**Comment by bonustrack** [comment]
Maybe instead of removing the background, you can use `bg-skin-bg` as color
