### ISSUE TITLE
bug: Starknet space creation show as failed while tx went through

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#409]
I've just created a space on Starknet mainnet, in the UI it show that the tx failed but when I look at the tx it looks good. Something is wrong, we should fix this.

<img width="424" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/d8dadcf7-5813-431b-8676-5f614438ff62">

Here is the tx:
https://starkscan.co/tx/0x25162bbc4d8d073b51e09070fe83a0b5236881c8d5b5fa4f6972e33933c9b81
Here is the space:
https://snapshot.box/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4

**Comment by Sekhmet** [comment]
@bonustrack this can happen if request in `watchForTransaction` fails. For example it used to happen if I used default Infura API key and it ended up being rate limited. Right now it should only happen if request failed 20 times.

What do you think the behaviour should be?
I'm thinking, we should have following failure scenarios, everything else would keep retrying.
1. We get receipt for transaction and we see it has REVERTED status.
2. We fail to get receipt for 20 times (in case transaction got dropped by the node somehow), unrelated failures (rate limits, API issues won't count and we would just keep repeating).
