### ISSUE TITLE
bug: input error style is broken

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#411]
There is an issue with the style of the error, check here when editing a strategy:
<img width="476" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/c8e90171-0b85-4569-9647-3f2d1d5567f9">

**Comment by Sekhmet** [comment]
Not sure what good workaround would be there for it as since https://github.com/snapshot-labs/sx-monorepo/pull/370 we use border to shift textarea contents down (but border is also used to display error).

@wa0x6e

**Comment by wa0x6e** [comment]
We could use `outline` or `shadow`. Will take a look at a workaround, maybe give the error style to an extra wrapper
