### ISSUE TITLE
bug(stamp): Stark.id domains doesn't resolve anymore on logged user section

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#438]
<img width="719" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/44e39afa-2c5c-42c2-a01b-44157c144ed8">

**Comment by ChaituVR** [comment]
I am not able to reproduce, 

<img width="269" alt="Untitled 2" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/69c47801-13fc-473d-9af8-1ec907f026d2">

Could you try again after hard refresh maybe?

**Comment by bonustrack** [comment]
Ok weird it works now, might be a cache issue, closing for now
