### ISSUE TITLE
feat: display vote reason

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#469]
We should show vote reasons on the proposal votes page.

The design in progress here: https://www.figma.com/design/hmHTau1Y1KYzrBBKLQr5QV/%23design?node-id=1243-10592&t=71jt6vYq9S496Vuz-0

**Comment by wa0x6e** [comment]
Waiting for PR about votes reason writing to be merged, else the API is not returning the indexed reason

**Comment by Sekhmet** [comment]
@bonustrack is this design for reason modal final so we can finish this task?



![Image](https://github.com/user-attachments/assets/d48e108a-bb19-48e5-af8d-476ab2ea4b51)
