### ISSUE TITLE
feat: add voter_count and proposer_count to spaces

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#48]
We should add the params `voter_count` in Space entity. This can be a param similar than `vote_count` but it only get increased when we find a new voter address based on the list of current voters on a space.

**Comment by Sekhmet** [comment]
Do we still want to add it? If we are adding `voter_count` do we what `proposer_count` as well maybe?

**Comment by Sekhmet** [comment]
I think with this https://github.com/snapshot-labs/sx-monorepo/issues/157 implemented it will be fairly easy and will work with out existing ORM.

**Comment by bonustrack** [comment]
@Sekhmet But for voter_count we will need to figure out on each new vote if it's a new unique user or not

**Comment by Sekhmet** [comment]
If for https://github.com/snapshot-labs/sx-monorepo/issues/157 we add entity `LeaderboardEntry` with ID of `SPACE_ID/USER_ID`, then we can fetch it on new vote or create new one.

If `LeaderboardEntry(spaceId, userId).vote_count === 0` then it's a new voter for this space and we can increase `voter_count`.

**Comment by bonustrack** [comment]
Ho right, got it, then that would be great to add `voter_count`
