### ISSUE TITLE
feat: delegateRegistryV1 support for offchain spaces

### ISSUE THREAD

**Issue by aurelianoB** [snapshot-labs/sx-monorepo#485]
# Background
Currently, Snapshot supports three types of delegation frameworks:
1. **checkpoint token delegation** (Compound or OZ-votes style)
2. **delegateRegistryV1** (Snapshot's delegation)
3. **delegateRegistryV2** (Split delegation)

Each framework has a different method for obtaining the delegated voting power:
- **Snapshot's delegation**: Queries delegations from Snapshot's subgraph and then computes voting power using the score-api.
- **Checkpoint token**s: Uses its own delegation subgraph, which can directly return total delegated voting power.
- **Split delegation**: Requires querying the subgraph and then using the score-api to apply voting power according to the desired strategy.

On the other hand, the sx-monorepo currently handles only the checkpoint token type of delegation, and only works for SX spaces. Note that a single space can support multiple delegations, e.g., one on Ethereum and another on Starknet.

# Objective

The objective of this task is to extend the delegation functionality to offchain spaces, only for delegateRegistryV1 framework for now. Specifically, we should support the same functionality currently available for SX spaces, i.e.:
- Display a list of delegates and the number of delegators and delegated voting power for each.
- Allow users to delegate to an address from the respective modal.

We will also support checkpoint token delegation in a separate issue (https://github.com/snapshot-labs/workflow/issues/161) this cycle. In the future, we will implement support for delegateRegistryV2 (https://github.com/snapshot-labs/workflow/issues/159).

# Steps to implement

- [ ] Add support for delegateRegistryV1 in offchain spaces

**Comment by bonustrack** [comment]
Here are more specs to support delegate API for "delegate" voting strategy:

We will need to code a service on this repository https://github.com/snapshot-labs/delegate-registry-api

This service should expose the same API that we have on https://github.com/snapshot-labs/delegates-api, ideally it should leverage the Checkpoint system to generate db from a simple GQL schema and expose the GraphQL API. 

This service should store delegates for each space with their voting power, to get the list of delegate we can use the leaderboard users from the space (meaning that we would only gather voting power for the delegate who ever voted or proposed on that space). This should work on demand, meaning that we would only store a list of delegate when it's being requested by a frontend.

**Comment by Sekhmet** [comment]
@bonustrack

I've setup a repository using Checkpoint that should handle DB and GraphQL side of this.
I've also created a middleware that intercepts requests and detects when governance information is queried (for example via `governance(id: "a")` or `delegates(where: { governance: "a" })`) and triggers a `compute` function with list of governances that need to be updated.

All this function should need to do is to query information from delegateRegistryV1 and convert it to `delegates-api` format (which I'm not sure is exactly needed as I didn't work on that codebase yet and haven't checked it either).

There is link to the file and to `compute` function:
https://github.com/snapshot-labs/delegate-registry-api/blob/59478ca415e909eee0f0d0d484bab2eadba2f809/src/compute.ts#L15-L34

We "just" need to query information we need and write it using Checkpoint models. If we have that API will be already available with the data we store.
