### ISSUE TITLE
bug: delegate tooltip doesn't close on mobile 

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/sx-monorepo#487]
Go to delegate pages on mobile, 
Click on new delegate button 
Notice that tooltip still appears on top
![Screenshot_2024-07-15-20-28-47-453_com.android.chrome.jpg](https://github.com/user-attachments/assets/a05d4ac5-1a9a-4c8a-9b98-6d6a61dbce8c)

**Comment by bonustrack** [comment]
Yes this is the case for all tooltip, I guess we need to remove them on mobile
