### ISSUE TITLE
bug: execution treasury appear on proposal without execution

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#490]
I tried to create a proposal without execution, but for some reason the execution treasury appear on the proposal page, we should remove it.
https://snapshot.box/#/sn:0x071977084d73002fed430d99108da39d241b900099ccc2a4cdcb7d5041d851d2/proposal/15

**Comment by ChaituVR** [comment]
I am not able to reproduce, you still see it? maybe share a screenshot

**Comment by Sekhmet** [comment]
Fixed in #491
