### ISSUE TITLE
bug: wrong voting power

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#492]
I tried to vote on this proposal with an Ethereum account: https://snapshot.box/#/sn:0x071977084d73002fed430d99108da39d241b900099ccc2a4cdcb7d5041d851d2/proposal/15/votes

For some reason it show on my vote that my voting power is ~0 NSTR while on the cast your vote section I see 1.1k NSTR. 
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/fe89cb55-145f-4abd-9be1-fcb1fa07ff55">

Also when I check the detail of my voting power it's about 110 and not 1.1k
<img width="531" alt="image" src="https://github.com/user-attachments/assets/1e27cb0f-396a-4faa-a4d8-73c0c4953ff7">

Here is the vote transaction: https://starkscan.co/tx/0x495e6fd313c1c0b44417ad86faf9bbb6c15192e819c0038bdbfff58506a0058

**Comment by ChaituVR** [comment]
I see wrong voting power on the transaction itself. so maybe something wrong happened while signing? 🙈

**Comment by Sekhmet** [comment]
> For some reason it show on my vote that my voting power is ~0 NSTR while on the cast your vote section I see 1.1k NSTR.

Looks like you voted before storage proofs were ready (voted on the proposals list) so you only got 1 VP from Whitelist strategy. This would have been improved with vote reason PR (because it shows you confirmation dialog with VP and here it would show it's still pending).

Looking into the rest.
