### ISSUE TITLE
bug: voting power is not resolving on active proposal

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#504]
I was still able to see an error with the voting power not resolving while the proposal started:

<img width="461" alt="image" src="https://github.com/user-attachments/assets/89a091d2-bc20-47cc-9499-16032706dab7">

In the log I can see this error message:

```
"revert_error": "Execution error: Execution failed. Failure reason: 0x566f7465733a20667574757265204c6f6f6b7570 ('Votes: future Lookup')."
```

**Comment by Sekhmet** [comment]
Is this something you can reproduce reliably or only sometimes? I cannot reproduce it now.

It can still happen if blocks take more than 10 minutes to produce, but not sure we can do much about it other than increase the delay further.
