### ISSUE TITLE
Infura API key exposed

### ISSUE THREAD

**Issue by pscott** [snapshot-labs/sx-monorepo#542]
I believe we expose our infura API key here.
I don't think it's a security issue but this means that anyone on the internet can use our key to DDOS or do malicious things with it.

https://github.com/snapshot-labs/sx-monorepo/blob/fa13652cde94a4513a4aaa457c733c7e8e7555f6/apps/api/src/overrrides.ts#L6

**Comment by bonustrack** [comment]
This key is known to be public, it's limited to 200k request per day and it's not used by us so all good.

**Comment by pscott** [comment]
So we provide this API key to the public is that it?

**Comment by bonustrack** [comment]
That's it, it just to make it easy to test locally, cost us $50/mo
