### ISSUE TITLE
feat: add network switcher for argent X

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#546]
Like we already do for EVM, we should trigger a wallet network switch on Starknet when the action is not on the correct chain.

This will avoid invalid signature with Argent X, when signing message on a different chainId than the wallet (braavos can sign message on any networks).

The wallet is supporting the networks switch call, see https://github.com/argentlabs/argent-x/blob/0607c5e58742dd33b3737e898ca78e97d7c4fb44/packages/dapp/src/services/wallet.service.ts#L250-L260

Feature should be implemented once:

- we have the correct chainId for the logged web3 object with https://github.com/snapshot-labs/sx-monorepo/pull/540
- we have a real-world code to test the switcher with https://github.com/snapshot-labs/sx-monorepo/pull/383

**Comment by Sekhmet** [comment]
We wanted to implement it before, but it didn't work back then (the call was ignored), we should verify if it's functional.

**Comment by wa0x6e** [comment]
Will check

**Comment by wa0x6e** [comment]
Regarding different actions support for starknet wallets: https://github.com/starknet-io/get-starknet/issues/212
