### ISSUE TITLE
bug: Proposals fail to load if execution is using gnosis chain

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/sx-monorepo#560]
- Proposals with execution on gnosis chain safe fail to load on local and throw error on snapshot.box
- If you go to http://localhost:8080/#/s:shutterdao0x36.eth/proposal/0x6f543fc4ba0e4d98bc4403fafb3bdb9b77838dea797af9a24f3a919b434621f7
It will fail to load
- If you go to  https://snapshot.box/#/s:shutterdao0x36.eth/proposal/0x6f543fc4ba0e4d98bc4403fafb3bdb9b77838dea797af9a24f3a919b434621f7 
It will throw an error:
```
TypeError: Cannot read properties of undefined (reading 'split')
    at setup (index-XAoAhxir.js:743:79014)
    at callWithErrorHandling (index-XAoAhxir.js:16:2216)
    at setupStatefulComponent (index-XAoAhxir.js:16:76447)
    at setupComponent (index-XAoAhxir.js:16:76085)
```

**Comment by ChaituVR** [comment]
I tried to look at it and found that we are missing gnosis here https://github.com/snapshot-labs/sx-monorepo/blob/fix-gnosis-chain-excecution/apps/ui/src/helpers/constants.ts#L5-L13 and later found that it is missing in many places 🤔 

maybe the easiest solution is just to add v-if on all UIBadgeNetwork? @Sekhmet

**Comment by wa0x6e** [comment]
If avatar is the only thing preventing us from supporting networks more dynamically, we could move it to stamp.

**Comment by Sekhmet** [comment]
> If avatar is the only thing preventing us from supporting networks more dynamically, we could move it to stamp.

We still need to map `chainId` -> `NetworkID` at the moment, which requires some hardcoded definitions. But I think it would be good not to have call `getNetwork` to get avatar and just use it from stamp directly, this way we can also display disabled networks.
