### ISSUE TITLE
style: add space breadcrumb on space pages

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#568]
As suggested by @Sekhmet we can add the space avatar and name on top left of the Space pages, it should have the same style and position than on the proposal page.
<img width="453" alt="image" src="https://github.com/user-attachments/assets/ad3c6188-a3b2-4ff8-ac70-b0be8c3fe986">

**Comment by ChaituVR** [comment]
How should we handle on mobile?

Looks like this:
![image](https://github.com/user-attachments/assets/6e330116-1ac5-4104-a91b-8030d5192234)
![image](https://github.com/user-attachments/assets/c20c3568-10bf-4a89-8a88-2f02741d067e)

We hide logo for now?
