### ISSUE TITLE
bug: NFT not showing up in treasury page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#589]
Somehow the list of NFT is empty on that treasury page while it should hold 2 NFTs

https://snapshot.box/#/eth:0x6E60b6dCc2923267104Bb4a68F4766f627430664/treasury

**Comment by ChaituVR** [comment]
Looks like openSea doesn't recognize these NFTs https://opensea.io/0x669477f3421F7dcA96F2DBaEDe538909BA465aA9/collected?search[chains][0]=ETHEREUM

**Comment by bonustrack** [comment]
> Looks like openSea doesn't recognize these NFTs [https://opensea.io/0x669477f3421F7dcA96F2DBaEDe538909BA465aA9/collected?search[chains][0]=ETHEREUM](https://opensea.io/0x669477f3421F7dcA96F2DBaEDe538909BA465aA9/collected?search%5Bchains%5D%5B0%5D=ETHEREUM)

I tried to send an NFT that is visible by default on OpenSea to that treasury but it also doesn't appear, must be something else.

**Comment by wa0x6e** [comment]
Do you have a link to a treasury with nft ?

**Comment by Sekhmet** [comment]
> I tried to send an NFT that is visible by default on OpenSea to that treasury but it also doesn't appear, must be something else.

What NFT did you send? This treasury's OpenSea account is still empty: https://opensea.io/0x669477f3421F7dcA96F2DBaEDe538909BA465aA9/collected

**Comment by Sekhmet** [comment]
We can reopen if it still reproduces.
