### ISSUE TITLE
feat: custom URL for treasury and NFTs on treasury page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#591]
Currently it's not possible to share the NFT page of a treasury with a direct link or another treasury, there is only a link to tokens of the first treasury like this:

https://snapshot.box/#/eth:0x6E60b6dCc2923267104Bb4a68F4766f627430664/treasury

We should have a link that send you to the NFTs page like this:

https://snapshot.box/#/eth:0x6E60b6dCc2923267104Bb4a68F4766f627430664/treasury/2/nfts

We can use the index of the treasury to show different treasury

**Comment by Sekhmet** [comment]
Fixed in https://github.com/snapshot-labs/sx-monorepo/pull/720
