### ISSUE TITLE
fix(ux): Add a loading indicator on editor

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/sx-monorepo#605]
https://github.com/user-attachments/assets/d2b60014-2d24-4ada-b649-ef7a12174b00

Go to any proposal creation page, 
https://snapshot.box/#/matic:0xcD4c00cAB0A86C182519e91a8b01b080B484C49B/create/0jk0cj

on load, it is not showing any indicator. if something is slow then it feels like something is broken

**Comment by wa0x6e** [comment]
Fixed by #822
