### ISSUE TITLE
bug: Cancel proposal doesn't work on off-chain spaces 

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/sx-monorepo#68]
Error in the console:
`Uncaught (in promise) Error: Network s-tn is read-only`

Proposal:
`s-tn:testsnap.eth/proposal/0x51b38754c4ec1e5cc141c25851f4ff1fe7041344148ede0d85dfbb5267e02ab2`

<img width="327" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/51686767/a85d2395-c583-4716-9f86-7f2b847fa3ae">

**Comment by wa0x6e** [comment]
yes, it's not implemented yet
