### ISSUE TITLE
Staknet signatures doesn't work with argent mobile

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/sx-monorepo#758]
It fail with this error:
![image](https://github.com/user-attachments/assets/96dbf5ca-63e9-4e65-908e-b79c07d38213)

To reproduce:

- Add this diff
```bash
diff --git a/apps/ui/src/composables/useActions.ts b/apps/ui/src/composables/useActions.ts
index e1a34b52..de408e42 100644
--- a/apps/ui/src/composables/useActions.ts
+++ b/apps/ui/src/composables/useActions.ts
@@ -43,6 +43,7 @@ export function useActions() {
           e.code === 'ACTION_REJECTED';
 
         if (!isUserAbortError) {
+          alert(`${e.message}\n${e.stack}`);
           uiStore.addNotification(
             'error',
             'Something went wrong. Please try again later.'
```
- Use vscode devtunnels to expose your dev port
- Open this URL in argent app

**Comment by bonustrack** [comment]
@ChaituVR Did you tried Starknet tx authenticator? Starknet signature authenticator is not whitelisted on Starknet official space cuz there was some issue with some wallets. But we should at least support Starknet tx on Argent mobile app.

**Comment by bonustrack** [comment]
Issue tracked here: https://github.com/snapshot-labs/workflow/issues/231
