### ISSUE TITLE
bug: unsupported treasury network

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#769]
Treasuries network is pulled from a small exhaustive list of networks on v2, compared to v1, which have a more broad networks support.

This is making v2 spaces using not recognized networks to fail, e.g https://snapshot.box/#/s:test.wa0x6e.eth/treasury/2/tokens

- Existing but not enabled network will fail with `Network XXX is not enabled`
- Unrecognized network will be just ignored (test space mentioned above has a third treasuries not shown, see https://hub.snapshot.org/api/spaces/test.wa0x6e.eth)

**Comment by wa0x6e** [comment]
See #830

**Comment by Sekhmet** [comment]
Will be covered by https://github.com/snapshot-labs/sx-monorepo/issues/830
