### ISSUE TITLE
ux: lag when resetting offchain space settings

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#791]
In the offchain space settings page, when cliking on the "Reset" button, it takes 1-2 seconds after clicking on the button before the bottom bar with the reset disappear, and the settings to reset.

This is due to "Reset" fetching the controller with an eth_call, instead of restoring it with the original value

This issue do not appear for onchain spaces

**Comment by wa0x6e** [comment]
@Sekhmet is there any reason to refetch the true online space controller on reset, compared to restoring original values from the hub ?

**Comment by wa0x6e** [comment]
This is making the reset pretty slow, and may take up to a few seconds, without any indication it's working.

I think we can sacrifice the live data when just resetting some dirty fields

**Comment by Sekhmet** [comment]
Of course we can address it, it's just matter of priority, this would also add some extra complexity as we would need to now also store initial state.

**Comment by wa0x6e** [comment]
> Of course we can address it, it's just matter of priority, this would also add some extra complexity as we would need to now also store initial state.

Maybe replacing the "Reset" button by a loading icon would suffice for now, as a very quick fix, wdyt ?

**Comment by Sekhmet** [comment]
We can do that.
