### ISSUE TITLE
refactor: Move S component into Ui

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/sx-monorepo#8]
As discussed with you @Sekhmet, we're going to deprecate the S folder and move the components into the Ui folder.

I propose renaming the components as follows:

1. `Base` -> `InputWrapper`
2. `IArray` -> `InputArray`
3. `IStamp` -> `InputStamp`
4. `IStampCover` -> `InputStampCover`
5. `IObject` -> `Form`
6. And so on

All these components would then obviously be used with the `Ui` prefix, e.g., `UiForm`. For the future, we might change `Ui` to `Base`, which will make things more readable as it avoids the double `iI` like in `UiInput` which is kinda hard to read in the normal VSCode UI font.

**Comment by Sekhmet** [comment]
I wonder if naming thing `UiInputArray` makes sense (vs `UiArrayInput`). For other things we seem to go second route (`ProposalsList`, `ProposalsListItem` where type is last and logical name is first).

**Comment by samuveth** [comment]
Using names like `InputText`, `InputNumber` groups our base components together and just makes it easier navigate. 

The way I see it that base Components are designed to be highly reusable across various parts of an application, with a focus on generic functionality (e.g., input fields, buttons). Their names often reflect their function or type directly, aiming for clarity and reusability.

Tightly Coupled Components, on the other hand, are often specific to a particular context or use case within the application (e.g., a list of proposals in a voting application). Their names tend to reflect their role within that specific context, which helps developers understand where and how they are used.

The key difference lies in the purpose and scope of use: base components are generic and broadly applicable, necessitating names that clearly describe their function or type, while tightly coupled components are context-specific, with names that convey their relationship to other components or their role within a specific part of the application.

**Comment by samuveth** [comment]
I also realized that `WrapperInput` makes more sense than `InputWrapper` it's just a wrapper for the inputs rather than an actual input

**Comment by Sekhmet** [comment]
> I also realized that WrapperInput makes more sense than InputWrapper as it's just a wrapper for the inputs rather than an actual input

I interpret it differently in my mind 😆 
- InputWrapper sounds like wrapper for inputs
- WrapperInput sounds like input for some wrapper(?) - this name is super confusing

But if we would go with both `InputWrapper` (which makes sense to me) and `InputString` for example (which kind of makes sense to me) then those two together are confusing still.

I think we can keep `Input` prefix for now, based on the fact that `SI` stands for Snapshot Input (?) so Input prefix is already there. Not sure what to do about wrapper, `WrapperInput` is not a good name, I'd just keep `InputWrapper` or `InputBase`.

**Comment by samuveth** [comment]
One is a Wrapper and the other is a Input, if we name Ui components like I did by their function or type first then `WrapperInput` is the only thing that makes sense. It might not read very nicely but if you consider reading it like `WrapperForInput` (same for `InputForString`) then it reads better.

**Comment by Sekhmet** [comment]
> One is a Wrapper and the other is a Input, if we name Ui components like I did by their function or type first then WrapperInput is the only thing that makes sense. It might not read very nicely but if you consider reading it like WrapperForInput (same for InputForString) then it reads better.

We should name things as clearly as possible, without the need of dictionary to be able to interpret things. It feels a bit we are replacing one inconsistent naming convention with different inconsistent naming convention.

Let's go for a compromise and go for `InputString` and `InputBase` 😆 

We can revisit it later just for that one case if we feel like it doesn't feel right.
