### ISSUE TITLE
bug: offchain delegations and treasuries are always save with ETH network

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#828]
Saving treasuries and delegations info on offchain space settings is ignoring network, and always save as ethereum

**Comment by wa0x6e** [comment]
Same issue is happning on other "network" params in offchain space settings, like the Delegation network.

All those fields are using short name like `eth`, `matic`, whereas v1 sequencer is expecting chain ID

**Comment by wa0x6e** [comment]
Will wait for #810 which is introducing a new component for network selection

**Comment by Sekhmet** [comment]
@wa0x6e I don't think we want to add just new extended network selector as unknown networks don't play nicely with treasuries.

We will need more groundwork on this front (https://github.com/snapshot-labs/sx-monorepo/issues/830), I was playing with solving this issue and it's quite a bit of refactor to get it right and see if we can get it prioritised this or next cycle.

Let's just fix this issue as-is for now.
