### ISSUE TITLE
refactor: refactor Block components 

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/sx-monorepo#9]
All folders are complete or have open PRs except `/Block`

Deprecate `/Block` folder and rename components:
1. `Actions` to `ProposalExecutionActions` or keep the `Block` in the naming with `ProposalBlockActions`
2. `ContactPicker` to `ContactPickerList`
3. `CreationConfirmation` to `CreateDeploymentProgress`
4. `Delegates` to `SpaceDelegates`
5. `Execution` to `ProposalExecutionsList`
6. `ExecutionEditable` to `EditorExecution`
7. `InfiniteScroller` to `UiContainerInifiniteScroll`
8. `NftPicker` to `SendNftPicker`
9. `SpaceFormController` to `CreateFormController` or `FormController`
10. `SpaceFormNetwork` to `CreateFormNetwork` or `FormNetwork`
11.  `SpaceFormVoting` to `CreateFormVoting` or `FormVoting`
12. `SpaceFormProfile` to `FormProfile` as it's used not only in Create
13. `SpaceFormStrategies` to `FormStrategies` as it's used not only in Create
14. `SpaceFormValidation` to `FormValidation` as it's used not only in Create
15. `StrategiesConfigurator` no rename just move
16. `TokenPicker` to `SendTokenPicker`

**Comment by Sekhmet** [comment]
That sounds good as well. Could you first document there all changes that you imagine we do? We can then discuss it and only then end up with a PR.

**Comment by samuveth** [comment]
Ok I will do that before I continue with the `/Block` directory

**Comment by samuveth** [comment]
@Sekhmet please review description

**Comment by Sekhmet** [comment]
> CreationConfirmation to CreateDeploymentProgress or CreateDeploymentOverview

`CreateDeploymentProgress` is good I think.

> ContactPicker to ContactPickerList
> NftPicker to SendNftPicker
> TokenPicker to SendTokenPicker

ContactPickerList feels a bit weird and inconsistent with `ProposalsList` and `TransactionsList`.
And also it's inconsistent with NftPicker and TokenPicker - why one of those ended up as list and others didn't?

I feel like I'd leave those as are **or** change those to `PickerContacts`, `PickerNft`, `PickerToken` (which would be consistent with naming for `Input`, `Indicator` etc.)

> SpaceFormController to CreateFormController or FormController
> SpaceFormNetwork to CreateFormNetwork or FormNetwork
> SpaceFormVoting to CreateFormVoting or FormVoting
> SpaceFormProfile to FormProfile as it's used not only in Create
> SpaceFormStrategies to FormStrategies as it's used not only in Create
> SpaceFormValidation to FormValidation as it's used not only in Create

I'd go for second option for consistency so every form has same naming convention.
