### ISSUE TITLE
validate `proposal threshold` in UI

### ISSUE THREAD

**Issue by pscott** [snapshot-labs/sx-monorepo#952]
One can input negative numbers for `proposal threshold` in UI as seen in the screenshot

<img width="445" alt="Screenshot 2024-10-30 at 16 37 34" src="https://github.com/user-attachments/assets/797c680f-f747-4886-b7dc-012a02171d80">

**Comment by ChaituVR** [comment]
`0` is a valid value? will allow anyone to create a proposal. so maybe I will add a minimum of `1`

**Comment by pscott** [comment]
i don't think `0` is necessarily `invalid`? Maybe someone could want to allow anyone to create a proposal?

**Comment by bonustrack** [comment]
I think at the contract level we don't enforce the value to be higher than 0, it could be 0 (but probably using -1 would fail). On the UI I'd be more into enforcing a number higher than 0 so we avoid setup that can be sybil attacked.

**Comment by ChaituVR** [comment]
> I think at the contract level we don't enforce the value to be higher than 0, it could be 0 (but probably using -1 would fail). On the UI I'd be more into enforcing a number higher than 0 so we avoid setup that can be sybil attacked.

Added a minimum of `1` here https://github.com/snapshot-labs/sx-monorepo/pull/955 so we can fight Sybil

**Comment by pscott** [comment]
idk who this Sybil guy is but I hate him
