### ISSUE TITLE
bug: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/sx-monorepo#997]
When i go to https://snapshot.box/#/home and connect my wallet `0x24F15402C6Bb870554489b2fd2049A85d75B982f` it throws this error in console 
<img width="574" alt="Untitled 4" src="https://github.com/user-attachments/assets/d44e66a6-a30e-41e3-951c-d10adb88864f">

**Comment by ChaituVR** [comment]
Can still reproduce on https://snapshot.box/#/explore

**Comment by Sekhmet** [comment]
I think it's because we didn't deploy new API to main endpoint.

**Comment by Sekhmet** [comment]
We deployed new API, shouldn't be the case anymore.
